# Generated by Django 4.1.7 on 2024-04-05 17:33

from django.db import migrations, models
import fileupload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('file_upload', models.FileField(null=True, upload_to=fileupload.models.user_directory_path)),
                ('image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
